services:
  - name: web-browser
    type: docker
    plan: starter
    dockerfileContents: |
      FROM ubuntu:20.04
      RUN apt-get update
      RUN apt-get install -y firefox
      EXPOSE 80
      CMD ["firefox"]
      
